name: C/C++ CI_UBUNTU

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: sudo apt update && sudo apt install mesa-common-dev libxrandr-dev libxrender-dev libxi-dev liblxi-dev libxfixes-dev libxxf86vm-dev libxext-dev libxinerama-dev libx11-xcb-dev libxau-dev libxdmcp-dev libxcursor-dev libglfw3-dev
      - name: sub
        run: git submodule update --init --recursive
      - name: cmake
        run: cd build && cmake .. && make
